### ISSUE TITLE
Tibetan font decompose ligatures.

### ISSUE THREAD

**Issue by RimeOCRLIB** [tmyroadctfig/xpdf#1]
Good day. 
First of all please accept our team deep gratitude for all your work for benefit of Open Source community and all world.

Our team are working with tibetan manuscripts and printed texts. Most part of tibetan fonts used dynamic ligatures.
This ligatures have not Unicode value and on that reason CMap of this fonts contain random Unicode value for this ligatures.

PDF files with this fonts we was not able convert to Unicode text by any XPDF tools or standard method. (Some ligatures are missed in output, some have random Unicode value)

This ligatures have unique names in font and pdftohtml generate correct font file with proper ligatures names. 

QUESTION:
**Does it possible to output in text every glyph name  instead Unicode value?**

At present we really need help with tibetan language PDF from Tibetan Bon tradition monastery. 

This PDF was formed in Tibet from manually inputed tibetan manuscripts. 
https://www.bsb-muenchen.de/fileadmin/_processed_/3/c/csm_998x400_cod_tibet_500_2r_28cf0505df.jpg
https://www.buddism.ru///work_file/PDF_BON_TRADITION/PDFtoHTML_output.png

Here it is link to one page document example.
https://www.buddism.ru///work_file/PDF_BON_TRADITION/_1_page.pdf

Here is original 2Mb file (one from hundred)
https://www.buddism.ru///work_file/PDF_BON_TRADITION/2010070919133295.pdf
Any advice, help and suggestion will be really appreciated.

May all be happy and healthy!

With best regards 
Open Source Buddhism Library
www.buddism.ru
Stroganov Alexander

**Comment by RimeOCRLIB** [comment]
On base of XPDF font parse logic it will be useful provide opportunity to set custom encoding  table in function

`Gfx8BitFont::Gfx8BitFont(XRef *xref, const char *tagA, Ref idA, GString *nameA,
			 GfxFontType typeA, Ref embFontIDA, Dict *fontDict):
  GfxFont(tagA, idA, nameA, typeA, embFontIDA)`
  
  this function already contain some opportunity to cMap reconstruction on base of glyph names. For now it is use 256 letter standard encoding. 
  Problem is it is need to read real POST (character code -> glyph name) table from embedded TrueType font.
  This encoding may contain few thousand glyphs.
  
  QUESTIONS:
 1. If construct correct cMap table for Gfx8BitFont in this function, does this font cMap produce correct Unicode output for ligatures? 
 2.  Does it possible to construct FoFiTrueType font in this function the same way how it construct Type1 fonts?
 3. How read actual POST table from it?
 
  ```
  FoFiType1 *ffT1;
  FoFiType1C *ffT1C;
  FoFiTrueType *ffTT;
  if (type == fontTrueType && embFontID.num >= 0) { 
        if ((buf = readEmbFontFile(xref, &len))) {
            if ((ffTT = FoFiTrueType::make(buf, len,0,gFalse))) {
                /***   how read character code  to character name (POST) table from  FoFiTrueType? ***/

            }
            gfree(buf);
        }
   }
```

**Comment by RimeOCRLIB** [comment]
On base of XPDF TrueType fonts parse logic it will be useful provide opportunity to set custom encoding  cMap table in function

`Gfx8BitFont::Gfx8BitFont(XRef *xref, const char *tagA, Ref idA, GString *nameA,
			 GfxFontType typeA, Ref embFontIDA, Dict *fontDict):
  GfxFont(tagA, idA, nameA, typeA, embFontIDA)`
  
  in this case toUnicode() function in Gfx8BitFont will provide correct Unicode for ligatures.
  
  This function already contain some opportunity to cMap reconstruction on base of glyph names. For now it is use 256 letter on base of standard encoding. 
  Problem is it is need to read real POST (character code -> glyph name) table from embedded TrueType font.
  This encoding table may contain few thousand glyphs. After we read this table we may provide correct cMap table on base of every glyph name.
  
  QUESTIONS:
 1. If construct correct cMap table for Gfx8BitFont in this function, does this font cMap produce correct Unicode output for ligatures in pdfToUnicode main function? 
 2. How read actual POST table from FoFiTrueType class?
 3. Gfx8BitFont have now short encoding (256 chars). TrueType font can contain full Unicode range + ligatures. 
 Would it possible to make encoding table in Gfx8BitFont larger or it is need produce another class from base GfxFont class?
 
  ```
  FoFiType1 *ffT1;
  FoFiType1C *ffT1C;
  FoFiTrueType *ffTT;
  if (type == fontTrueType && embFontID.num >= 0) { 
        if ((buf = readEmbFontFile(xref, &len))) {
            if ((ffTT = FoFiTrueType::make(buf, len,0,gFalse))) {
               
                /***   how read character code to character name (POST) table from  FoFiTrueType? ***/

            }
            gfree(buf);
        }
   }
```
PROBLEM:
Microsoft Himalaya font used POST table of version 3. 
`postFmt == 0x00030000` 
in 
`void FoFiTrueType::readPostTable()`

In official Microsoft page it is reference to version 3 f POST table:
```
Version 3.0

This version makes it possible to create a font that is not burdened 
with a large 'post' table set of glyph names. (!)

A version 3.0 'post' table can be used by OpenType fonts with TrueType or CFF (version 1 or 2) data.

This version specifies that no PostScript name information is provided for the glyphs in this font file. 
The printing behavior of this version on PostScript printers is unspecified, except that it should not 
result in a fatal or unrecoverable error. Some drivers may print nothing; other drivers may attempt 
to print using a default naming scheme.

Windows makes use of the italic angle value in the 'post' table but does not actually require any 
glyph names to be stored as Pascal strings.
```
**How obtain a glyph name <-> glyph index ?**

commentary from ot-font users:
Currently otf-font gets glyph names from post table only, but since fonts with CFF table use post version 3 we don’t get any glyph names for such fonts and need to get them from the CFF table.

https://github.com/harfbuzz/harfbuzz/issues/2052

Here it is explanation how parse CFF fonts (POST table version 3) 
http://pomax.github.io/CFF-glyphlet-fonts/

Would it possible to use freetype library for this task? (#include <ft2build.h>)
This library already used in SplashFTFont.cc
Something like this may by?
https://tools.ietf.org/doc/libfreetype6/tutorial/step1.html

**Comment by RimeOCRLIB** [comment]
Does it possible to use xpdfrc − configuration file for Xpdf tools on purpose of this cMap for decomposing ligatures problem correction?
How install this nameToUnicode correction table for every font (it is about 50 of tibetan fonts)?
from XPDF reference:
```
nameToUnicode map−file

Specifies a file with the mapping from character names to Unicode. 
This is used to handle PDF fonts that have valid encodings but no ToUnicode entry. 
Each line of a nameToUnicode file looks like this:

hex−string name

The hex−string is the Unicode (UCS-2) character index, and name is the corresponding character name. 
Multiple nameToUnicode files can be used; if a character name is given more than once, the code 
in the last specified file is used. There is a built-in default nameToUnicode table with 
all of Adobe’s standard character names.
```

**Comment by RimeOCRLIB** [comment]
**UPDATE.**
This Microsoft font have not glyph names at all. GlyphXXX and UniXXX names it is temporary names which FontForge substituted for glyph which exist in font but not have name. 
GlyphXXX used if it is no Unicode value in glyph and UniXXX if glyph have no name but have unicode value.

As result in Microsoft Himalaya font decomposed ligatures have no name and have no Unicode. All we have from PDF file embedded font it is CID index of this ligature which depends from how many letters from original font was used in PDF document.

Any idea does it exist any method to identify this ligature glyphs between original font and partial font embedded in PDF?

**Comment by tmyroadctfig** [comment]
Hi, this repository is an unofficial copy of the code from the XPDF website with a few changes required by my employer back when we were using XPDF in our product. It's not actively maintained, and seemed to be out of date compared to the latest XPDF released.

I think the best place to ask these questions might be over on the XPDF forum page: https://forum.xpdfreader.com/

I'm going to archive this repo now to avoid further confusion.

Best regards,
Luke
